FROM registry.access.redhat.com/ubi8-minimal

RUN microdnf update -y && \
    microdnf install -y bind-utils iputils net-tools iproute
#    dnf install -y bind-utils iputils net-tools traceroute iproute

CMD tail -f /dev/null
