apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: anyuid provides all features of the restricted SCC
      but allows users to run with any UID and any GID.
  generation: 1
  name: netraw

allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
  - NET_RAW
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- '*'
# - MKNOD
# - SETGID
# - SETFCAP
# - SETPCAP
# - SETUID
# - AUDIT_CONTROL
# - AUDIT_WRITE
# - BLOCK_SUSPEND
# - CHOWN
# - DAC_OVERRIDE
# - DAC_READ_SEARCH
# - FOWNER
# - FSETID
# - IPC_LOCK
# - IPC_OWNER
# - KILL
# - LEASE
# - LINUX_IMMUTABLE
# - MAC_ADMIN
# - MAC_OVERRIDE
# - NET_ADMIN
# - NET_BROADCAST
# - NET_RAW
# - SYS_ADMIN
# - SYS_BOOT
# - SYS_CHROOT
# - SYS_MODULE
# - SYS_NICE
# - SYS_PACCT
# - SYS_PTRACE
# - SYS_RAWIO
# - SYS_RESOURCE
# - SYS_TIME
# - SYS_TTY_CONFIG
# - SYSLOG
# - WAKE_ALARM

runAsUser:
  type: RunAsAny

seLinuxContext:
  type: MustRunAs

supplementalGroups:
  type: RunAsAny
users: []
volumes:
# - configMap
# - downwardAPI
- emptyDir
# - persistentVolumeClaim
# - projected
# - secret